### ISSUE TITLE
date-picker has no min-date or max-date ?

### ISSUE THREAD

**Issue by anchengjian** [myplanet/angular-date-picker#12]
date-picker has no  `min-date` or `max-date` ,
If I'm wrong, then how can I use it?
thx~

**Comment by atesgoral** [comment]
The thinking behind angular-date-picker was to make it lightweight and offload concerns like parsing, formatting, validation to integrations. Min/max date range could be enforced by validation of the value retrieved through and ngModel (e.g. a text field that is linked to the date picker). Would that work for you?

**Comment by anchengjian** [comment]
I got it, thx~~
