### ISSUE TITLE
Wrong firstDayOfWeek with $locale

### ISSUE THREAD

**Issue by nicmae** [myplanet/angular-date-picker#13]
It seems that $locale follows ISO8601 standard for DATETIME_FORMATS.FIRSTDAYOFWEEK (*https://github.com/angular/angular.js/issues/11900*).

As results, 0 is monday, 1 is sunday for $locale. As the picker is based on the javascript standard, the date-picker is reversed when $locale is used.

**Comment by atesgoral** [comment]
Thanks for reporting!

**Comment by atesgoral** [comment]
I guess you meant 6 is Sunday, right? https://github.com/angular/angular.js/blob/master/src/ngLocale/angular-locale_en-us.js#L45

**Comment by nicmae** [comment]
Yes, correct. My mistake :)
Thanks for your reactivity!

**Comment by atesgoral** [comment]
The fix is now included in v1.3.2.
