### ISSUE TITLE
Wrong first day of week when $locale.DATETIME_FORMATS.FIRSTDAYOFWEEK is 0

### ISSUE THREAD

**Issue by mattgoldspink** [myplanet/angular-date-picker#14]
The logic should be:

firstDayOfWeek = ($locale.DATETIME_FORMATS.FIRSTDAYOFWEEK != null ?
                                        $locale.DATETIME_FORMATS.FIRSTDAYOFWEEK : 6) + 1 % 7

Otherwise any countries who use Monday as the first day of the week come out as Sunday

**Comment by atesgoral** [comment]
This should be fixed by 76293fd6b24f818d442a79da56daaf43ee1b9d7c included in v1.3.2.

**Comment by mattgoldspink** [comment]
Unfortunately not because if $locale.DATETIME_FORMATS.FIRSTDAYOFWEEK is set to 0 then the following expression always results in 6 which isn't correct:

`($locale.DATETIME_FORMATS.FIRSTDAYOFWEEK || 6)`

Hence the need for an explicit null check.

**Comment by atesgoral** [comment]
Ouch! On a closer inspection I saw my error. Thanks for pointing it out! A fix will come shortly...

**Comment by atesgoral** [comment]
@mattgoldspink The fix is now on v1.3.4.

**Comment by mattgoldspink** [comment]
Thanks @atesgoral
