### ISSUE TITLE
No minimum and maximum date restriction setting.

### ISSUE THREAD

**Issue by charublaze** [myplanet/angular-date-picker#17]
How to include minimum maximum date restriction?

**Comment by di3orlive** [comment]
+1

**Comment by atesgoral** [comment]
This could be a useful feature.

Perhaps an `allow-date` etc. attribute that takes a callback with a date as an argument, returning `true` to make a date selectable. This could be a more flexible solution than a min/max approach (e.g. you could disallow selection of statutory holidays and weekends).

@unframework, @paracycle, @d9su opinions?
